# SEND BY DIRECT EXCHANGE
POST http://localhost:8080/api/rabbitmq/direct-exchange
Content-Type: application/json

{
  "paymentId": 55,
  "paymentType": "fake_data",
  "paymentStatus": "fake_data",
  "paymentAmount": 8.65,
  "paymentCurrency": "fake_data"
}