server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    queues:
      default:
        name: spring-boot-queue
        routing-key: spring-boot-routing-key
        exchange: spring-boot-exchange
        durable: false