server:
    port: 8080
spring:
    rabbitmq:
        host: localhost
        port: 5672
        password: guest
        username: guest
        queues:
            default:
                durable: false
                exchange: spring-boot-exchange
                name: spring-boot-queue
                routing-key: spring-boot-routing-key